# Generated by Django 4.1 on 2023-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Eléctricité', 'Eléctricité'), ('Plomberie', 'Plomberie'), ('Matériels et divers', 'Matériels et divers')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
